### ISSUE TITLE
Add Function of the DigiConverter

### ISSUE THREAD

**Issue by Geeks-Arpan** [Rohan-450/Digiconvert-Calculator#1]
![DigiConverter](https://github.com/Rohan-450/Digiconvert-Calculator/assets/99377659/8dc3df23-c594-47b2-b3df-88bd133ccdd0)

**Comment by YooAshu** [comment]
i want to work on this issue

**Comment by Rohan-450** [comment]
Hello @YooAshu this issue is opened by someone else cuz he was giving inputs through keyboard and it wasn't working .
We need to specifically give inputs by clicking the buttons so this issue will be closed. Thank you for ur interest but u can work on ur previous issue or create anything new. Happy Contributing!
